### ISSUE TITLE
在iPad上的Safari浏览器9999难用！

### ISSUE THREAD

**Issue by Gtd232** [Nightscratch/Visual-block-programming#1]
拖动不了积木！这恐怖！  
我所使用的是iPad上的Safari！  
求9999修复！

https://user-images.githubusercontent.com/79702405/216775890-01bc4482-f533-45ee-b11a-c57b02be0cab.mp4

**Comment by Nightscratch** [comment]
哦哦哦，等我9999做完了，就999兼容Safari
